[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

    [build]
    command = "npm install --legacy-peer-deps && npm run build"
    publish = "dist" # or "build" if using create-react-app
